version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 25800:25800
    command:
      sh -c 'npm i && npm start'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    ports:
      - 25801:8080
    command:
      sh -c 'npm i && npm run serve'
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    ports:
      - 25802:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql_db
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_db:/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
  redis:
    image: redis
    ports:
      - 25803:6379
volumes:
  mysql_db: {}
